{
 "title": "drc-master2",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Transition Success Count",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(drc_v2_master_v2_sync_counter{result=\"success\", task=~\"ALL\"}[60s])) by (pipeline)",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Transition Error Count",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(drc_v2_master_v2_sync_counter{result=\"error\", task!~\"ALL\"}[1m])) by (pipeline, task)",
     "legendFormat": "{{pipeline}}-{{task}}"
    }
   ]
  },
  {
   "title": "master check Process Down",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(drc_v2_master_v2_process_down[1m])) by (pipeline,task)",
     "legendFormat": "{{pipeline}}: {{task}}"
    }
   ]
  },
  {
   "title": "Schedule Duration 80%",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(drc_v2_master_v2_schedule_duration_seconds_bucket[1m])) by (le, pipeline))",
     "legendFormat": "{{pipeline}}"
    }
   ]
  }
 ]
}