{
 "title": "drc-pipeline-mysql-mysql",
 "description": "drc pipeline for mysql to tidb",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pipeline_prefix",
    "query": "core,sandbox,gdpr,mysql2mysql,data,json_data,mysql2tidb"
   }
  ]
 },
 "panels": [
  {
   "title": "Gravity binlog latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "binlog_latency_from_gravity_80_percent",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(drc_v2_gravity_binlog_duration_seconds_from_gravity_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le,pipeline))",
       "legendFormat": "{{pipeline}}"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(drc_v2_gravity_binlog_duration_seconds_from_gravity_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le))",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "binlog_latency_from_gravity_95_percent",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(drc_v2_gravity_binlog_duration_seconds_from_gravity_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le,pipeline))",
       "legendFormat": "{{pipeline}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(drc_v2_gravity_binlog_duration_seconds_from_gravity_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le))",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "binlog_latency_from_gravity_99_percent",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(drc_v2_gravity_binlog_duration_seconds_from_gravity_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le,pipeline))",
       "legendFormat": "{{pipeline}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(drc__v2_gravity_binlog_duration_seconds_from_gravity_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le))",
       "legendFormat": "average"
      }
     ]
    }
   ]
  },
  {
   "title": "Gravity Message process latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gravity Message Process Duration 80%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(drc_v2_gravity_handle_msg_duration_seconds_bucket{pipeline=~'$pipeline_prefix.*',stage='all'}[1m])) by (le,pipeline, instance))",
       "legendFormat": "{{pipeline}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Gravity Message Process Duration 95%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(drc_v2_gravity_handle_msg_duration_seconds_bucket{pipeline=~'$pipeline_prefix.*',stage='all'}[1m])) by (le,pipeline,instance))",
       "legendFormat": "{{pipeline}}@{{instance}}-{{stage}}"
      }
     ]
    },
    {
     "title": "Gravity Message Process Duration 99%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(drc_v2_gravity_handle_msg_duration_seconds_bucket{pipeline=~'$pipeline_prefix.*',stage='all'}[1m])) by (le,pipeline, instance))",
       "legendFormat": "{{pipeline}}@{{instance}}-{{stage}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gravity qps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "scheduler_enqueue_qps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(drc_v2_gravity_scheduler_enqueue{pipeline=~'$pipeline_prefix.*'}[1m])) by (pipeline, instance)",
       "legendFormat": "{{pipeline}}@{{instance}}"
      }
     ]
    },
    {
     "title": "scheduler_dequeue_qps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(drc_v2_gravity_scheduler_dequeue{pipeline=~'$pipeline_prefix.*'}[1m])) by (pipeline, instance)",
       "legendFormat": "{{pipeline}}@{{instance}}"
      }
     ]
    },
    {
     "title": "kafka_enqueue_qps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(drc_v2_gravity_kafka_enqueue{pipeline=~'$pipeline_prefix.*'}[1m])) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "kafka_success_qps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(drc_v2_gravity_kafka_success{pipeline=~'$pipeline_prefix.*'}[1m])) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gravity others (errors/queue length)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "kafka_error",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ]
    },
    {
     "title": "scheduler queue length",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "drc_v2_gravity_scheduler_enqueue - on(instance, pipeline) drc_v2_gravity_scheduler_dequeue{pipeline=~'$pipeline_prefix.*'}",
       "legendFormat": "{{pipeline}}"
      }
     ]
    },
    {
     "title": "kafka partition rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(drc_v2_gravity_partition_counter{pipeline=~'$pipeline_prefix.*'}[1m])",
       "legendFormat": "{{topic}}-{{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "nuclear kafka offset lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "kafka offset lag",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(drc_v2_nuclear_offset_lag{pipeline=~'$pipeline_prefix.*'}) by (pipeline, topic, partition)",
       "legendFormat": "{{pipeline}}-{{topic}}-{{partition}}"
      }
     ]
    },
    {
     "title": "nuclear kafka tps",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(drc_v2_nuclear_kafka_msg_count{pipeline=~'$pipeline_prefix.*'}[1m])) by (pipeline, topic, partition)",
       "legendFormat": "{{topic}}-{{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "nuclear receive latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "80_percent_duration_gravity_sent_to_nuclear_receive",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(drc_v2_nuclear_receive_msg_duration_seconds_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le,pipeline))",
       "legendFormat": "{{pipeline}}"
      }
     ]
    },
    {
     "title": "95_percent_duration_gravity_sent_to_nuclear_receive",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(drc_v2_nuclear_receive_msg_duration_seconds_bucket{pipeline='$pipeline_prefix.*'}[1m])) by (le,pipeline))",
       "legendFormat": "{{pipeline}}"
      }
     ]
    },
    {
     "title": "99_percent_duration_gravity_sent_to_nuclear_receive",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(drc_v2_nuclear_receive_msg_duration_seconds_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le,pipeline))",
       "legendFormat": "{{pipeline}}"
      }
     ]
    }
   ]
  },
  { "title": "nuclear sql commit latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "80% Nuclear Sql commit duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(drc_v2_nuclear_sql_commit_duration_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le,pipeline,stage))",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "95% Nuclear Sql commit duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(drc_v2_nuclear_sql_commit_duration_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le,pipeline,stage))",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "99% Nuclear Sql commit duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(drc_v2_nuclear_sql_commit_duration_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le,pipeline,stage))",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "nuclear done latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "80_percent_duration_gravity_sent_to_nuclear_done",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(drc_v2_nuclear_e2e_handle_msg_duration_seconds_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le,pipeline))",
       "legendFormat": "{{pipeline}}"
      }
     ]
    },
    {
     "title": "95_percent_duration_gravity_sent_to_nuclear_done",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(drc_v2_nuclear_e2e_handle_msg_duration_seconds_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le,pipeline))",
       "legendFormat": "{{pipeline}}"
      }
     ]
    },
    {
     "title": "99_percent_duration_gravity_sent_to_nuclear_done",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(drc_v2_nuclear_e2e_handle_msg_duration_seconds_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le,pipeline))",
       "legendFormat": "{{pipeline}}"
      }
     ]
    }
   ]
  },
  { "title": "nuclear sql commit qps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Nuclear sql commit qps",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(drc_v2_nuclear_sql_commit_count{pipeline=~'$pipeline_prefix.*'}[1m])) by (pipeline)",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Nuclear sql commit batch size",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(drc_v2_nuclear_sql_commit_batch_size{pipeline=~'$pipeline_prefix.*'}) by (db)",
     "legendFormat": "{{db}}"
    }
   ]
  },
  { "title": "Nuclear sliding window", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "sliding window ration",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(drc_v2_nuclear_sliding_window_ratio{pipeline=~'$pipeline_prefix.*'}) by (topic, partition)",
     "legendFormat": "{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "sliding window size",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "drc_v2_nuclear_sliding_window_size{pipeline=~'$pipeline_prefix.*'}",
     "legendFormat": "{{topic}}-{{partition}}"
    }
   ]
  },
  { "title": "scanner latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "scanner batch query durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(drc_v2_scanner_batch_query_duration_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le,pipeline))",
     "legendFormat": "{{pipeline}}---bacth_query_durations"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(drc_v2_scanner_single_scan_duration_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le,pipeline))",
     "legendFormat": "{{pipeline}}---single_scan_duration"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(drc_v2_scanner_send_job_duration_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le,pipeline))",
     "legendFormat": "{{pipeline}}---send_job_duration"
    }
   ]
  },
  { "title": "scanner queue length", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "scanner queue length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "drc_v2_scanner_queue_length" }
   ]
  },
  {
   "title": "scanner kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "scanner kafka qps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(drc_v2_scanner_kafka_enqueue{pipeline=~'$pipeline_prefix.*'}[1m])",
       "legendFormat": "{{pipeline}}"
      }
     ]
    },
    {
     "title": "scanner kafka partition rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(drc_v2_scanner_partition_counter{pipeline=~'$pipeline_prefix.*'}[1m])",
       "legendFormat": "{{topic}}-{{partition}}"
      }
     ]
    }
   ]
  },
  { "title": "scanner worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "scanner worker queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(drc_v2_worker_pool_queue_size{pipeline=~'$pipeline_prefix.*',component='scanner'})",
     "legendFormat": "averge queue size"
    }
   ]
  },
  {
   "title": "worker tps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(drc_v2_worker_pool_processed_job_count{pipeline=~'$pipeline_prefix.*',component='scanner'}[1m])) by (pipeline)"
    }
   ]
  },
  {
   "title": "worker average batch size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(drc_v2_worker_pool_batch_size{pipeline=~'$pipeline_prefix.*',component='scanner'})"
    }
   ]
  },
  { "title": "scanner worker latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "80% worker latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(drc_v2_worker_pool_job_process_latency_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le,pipeline))"
    }
   ]
  },
  {
   "title": "90% worker latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(drc_v2_worker_pool_job_process_latency_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le,pipeline))"
    }
   ]
  },
  {
   "title": "99% worker latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(drc_v2_worker_pool_job_process_latency_bucket{pipeline=~'$pipeline_prefix.*'}[1m])) by (le,pipeline))"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "worker_pool error count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "drc_v2_worker_pool_error_count{pipeline=~'$pipeline_prefix.*',stage='all'}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "worker pool sliding window ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(drc_v2_worker_pool_sliding_window_ratio{pipeline=~'$pipeline_prefix.*',component='scanner'})",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "worker pool sliding window size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(drc_v2_worker_pool_sliding_window_size{pipeline=~'$pipeline_prefix.*',component='scanner'})"
    }
   ]
  }
 ]
}