{
 "title": "Gravity Pipeline Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Event Time Low Watermark (E2E Latency)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.8, sum(rate(gravity_event_time_latency_bucket[1m])) by (le, pipeline))",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Process Time Low Watermark (Internal Latency)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.8, sum(rate(gravity_process_time_latency_bucket[1m])) by (le, pipeline))",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Output Msg Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gravity_output_counter[1m])) by (pipeline)",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Output Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.8, sum(rate(gravity_output_latency_bucket[1m])) by (le, pipeline))",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gravity_queue_length) by (pipeline)",
     "legendFormat": "{{pipeline}}"
    }
   ]
  }
 ]
}