{
 "title": "Gravity Pipeline Detail",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "pipeline",
    "query": "label_values(gravity_input_emitter_counter, pipeline)"
   }
  ]
 },
 "panels": [
  {
   "title": "80% Low Watermark",
   "type": "graph",
   "description": "event time = update time at source - end time\n\nprocess time= receive time at gravity - end time\n\nend time: the time point when a specific row and all its proceedings has been successfully written",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.8, sum(rate(gravity_event_time_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "event time"
    },
    {
     "expr": "histogram_quantile(0.8, sum(rate(gravity_process_time_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "process time"
    }
   ]
  },
  {
   "title": "95% Low Watermark",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gravity_event_time_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "event time"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gravity_process_time_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "process time"
    }
   ]
  },
  {
   "title": "80% Latency",
   "type": "graph",
   "description": "latency within each component",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.8, sum(rate(gravity_input_probe_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "probe"
    },
    {
     "expr": "histogram_quantile(0.8, sum(rate(gravity_input_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "input"
    },
    {
     "expr": "histogram_quantile(0.8, sum(rate(gravity_emitter_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "emitter"
    },
    {
     "expr": "histogram_quantile(0.8, sum(rate(gravity_scheduler_total_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "scheduler total"
    },
    {
     "expr": "histogram_quantile(0.8, sum(rate(gravity_scheduler_submit_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "scheduler submit"
    },
    {
     "expr": "histogram_quantile(0.8, sum(rate(gravity_scheduler_ack_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "scheduler ack"
    },
    {
     "expr": "histogram_quantile(0.8, sum(rate(gravity_output_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "output"
    },
    {
     "expr": "histogram_quantile(0.8, sum(rate(gravity_input_after_commit_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "after-commit"
    }
   ]
  },
  {
   "title": "100% Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(gravity_input_probe_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "probe"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(gravity_input_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "input"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gravity_emitter_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "emitter"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(gravity_scheduler_total_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "scheduler total"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(gravity_scheduler_submit_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "scheduler submit"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(gravity_scheduler_ack_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "scheduler ack"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(gravity_output_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "output"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(gravity_input_after_commit_latency_bucket{pipeline='$pipeline'}[1m])) by (le))",
     "legendFormat": "after-commit"
    }
   ]
  },
  {
   "title": "Event Per Second",
   "type": "graph",
   "description": "throughput of each component",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gravity_input_counter{pipeline='$pipeline'}[1m]))",
     "legendFormat": "input"
    },
    {
     "expr": "sum(irate(gravity_input_emitter_counter{pipeline='$pipeline'}[1m]))",
     "legendFormat": "input-emitter"
    },
    {
     "expr": "sum(irate(gravity_emitter_scheduler_counter{pipeline='$pipeline'}[1m]))",
     "legendFormat": "emitter-scheduler"
    },
    {
     "expr": "sum(irate(gravity_scheduler_output_counter{pipeline='$pipeline'}[1m]))",
     "legendFormat": "scheduler-output"
    },
    {
     "expr": "sum(irate(gravity_output_counter{pipeline='$pipeline'}[1m]))",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "actual batch size",
   "type": "graph",
   "description": "actual batch size for output",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(gravity_scheduler_batch_size{pipeline='$pipeline'})"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "graph",
   "description": "length of all kinds of internal queues",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gravity_queue_length{pipeline='$pipeline'}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Input Detail",
   "type": "graph",
   "description": "throughput of different tables in input component",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gravity_input_counter{pipeline='$pipeline', type!='ctl'}[1m]))",
     "legendFormat": "total(not ctl)"
    },
    {
     "expr": "sum(irate(gravity_input_counter{pipeline='$pipeline', type='ctl'}[1m]))",
     "legendFormat": "ctl"
    },
    {
     "expr": "sum(irate(gravity_input_counter{pipeline='$pipeline', type!='ctl'}[1m])) by (db, table)",
     "legendFormat": "{{db}}.{{table}}"
    }
   ]
  },
  {
   "title": "Output Detail",
   "type": "graph",
   "description": "throughput of different output target",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gravity_output_counter{pipeline='$pipeline'}[1m])) by (cat0, cat1)",
     "legendFormat": "{{cat0}}.{{cat1}}"
    },
    {
     "expr": "sum(irate(gravity_output_counter{pipeline='$pipeline'}[1m]))",
     "legendFormat": "total "
    },
    {
     "expr": "sum(irate(gravity_scheduler_flush_stats{pipeline='$pipeline'}[1m])) by (table, stats)",
     "legendFormat": "{{table}}-flush-{{stats}}"
    }
   ]
  }
 ]
}