FROM frolvlad/alpine-glibc

COPY alpine.repositories /etc/apk/repositories

RUN apk update && apk upgrade && apk add bash && apk add tzdata

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone

WORKDIR /

COPY bin/gravity-operator-linux-amd64 /drc-operator