name = "example-mongo2kafka"

[input]
type = "mongo"
mode = "stream"

[input.config.source]
host = "127.0.0.1"
port = 27017

[output]
type = "async-kafka"

[output.config.kafka-global-config]
broker-addrs = ["localhost:9092"]

[[output.config.routes]]
match-schema = "test"
match-table = "test_table"
dml-topic = "test.test_table"

[scheduler]
type = "batch-table-scheduler"
[scheduler.config]
nr-worker = 1
batch-size = 2
queue-size = 1024
sliding-window-size = 1024
